var LE_TOPICS = [
  { title: "El Teorema de Pitágoras explicado de forma sencilla", cat: "Matemáticas", path: "mathematik/satz-des-pythagoras.html", keywords: "teorema pitagoras triangulo hipotenusa cateto geometria angulo recto" },
  { title: "Las Fracciones explicadas de forma sencilla", cat: "Matemáticas", path: "mathematik/brueche.html", keywords: "fracciones numerador denominador sumar fraccion" },
  { title: "Los Números Primos explicados de forma sencilla", cat: "Matemáticas", path: "mathematik/primzahlen.html", keywords: "numero primo teoria de numeros divisible" },
  { title: "El Problema de Monty Hall explicado de forma sencilla", cat: "Matemáticas", path: "mathematik/drei-tueren-problem.html", keywords: "monty hall problema puertas probabilidad cabra" },
  { title: "¿Por qué cada orden de cartas barajado es único?", cat: "Matemáticas", path: "mathematik/kartenspiel-wahrscheinlichkeit.html", keywords: "cartas baraja mezclar factorial 52 probabilidad" },
  { title: "La Gravedad explicada de forma sencilla: Por qué una bala disparada aterriza tan rápido como una que se deja caer", cat: "Física", path: "physik/gravitation-abschuss.html", keywords: "gravedad bala caida disparo movimiento" },
  { title: "La Velocidad de Caída explicada de forma sencilla", cat: "Física", path: "physik/fallgeschwindigkeit.html", keywords: "caida libre velocidad caer" },
  { title: "Las Mareas explicadas de forma sencilla", cat: "Física", path: "physik/ebbe-und-flut.html", keywords: "mareas luna marea alta marea baja" },
  { title: "Por qué la Tierra es una esfera y no un disco", cat: "Física", path: "physik/erde-ist-eine-kugel.html", keywords: "tierra esfera disco astronomia redonda" },
  { title: "La Diferencia entre Voltios, Amperios y Vatios explicada de forma sencilla", cat: "Física", path: "physik/volt-ampere-watt.html", keywords: "voltio amperio vatio electricidad tension corriente potencia" },
  { title: "La Masa y la Densidad explicadas de forma sencilla", cat: "Física", path: "physik/masse-und-dichte.html", keywords: "masa densidad peso volumen flotar hundir" },
  { title: "La Palanca (Ley de la Palanca) explicada de forma sencilla", cat: "Física", path: "physik/hebelwirkung.html", keywords: "palanca ley de la palanca balancin brazo de fuerza" },
  { title: "La Fuerza Centrípeta y Centrífuga explicadas de forma sencilla", cat: "Física", path: "physik/zentripetalkraft-zentrifugalkraft.html", keywords: "fuerza centripeta fuerza centrifuga movimiento circular curva" },
  { title: "El Gato de Schrödinger explicado de forma sencilla", cat: "Física", path: "physik/schroedingers-katze.html", keywords: "schrodinger gato mecanica cuantica superposicion fisica cuantica" },
  { title: "El Desplazamiento de Agua explicado de forma sencilla", cat: "Física", path: "physik/wasserverdraengung.html", keywords: "desplazamiento de agua arquimedes flotabilidad flotar hundir densidad" },
  { title: "Darwin y la Teoría de la Evolución explicada de forma sencilla", cat: "Biología", path: "biologie/evolutionstheorie.html", keywords: "darwin evolucion seleccion natural mutacion especie" },
  { title: "El ADN explicado de forma sencilla", cat: "Biología", path: "biologie/dna.html", keywords: "adn genoma doble helice genes pares de bases genetica" },
  { title: "Los Virus explicados de forma sencilla", cat: "Biología", path: "biologie/viren.html", keywords: "virus microbiologia celula huesped vacuna material genetico" },
  { title: "Las Bacterias explicadas de forma sencilla", cat: "Biología", path: "biologie/bakterien.html", keywords: "bacterias microbiologia procariotas division celular antibioticos" },
  { title: "Las Células Madre explicadas de forma sencilla", cat: "Biología", path: "biologie/stammzellen.html", keywords: "celulas madre biologia celular embrionarias adultas medula osea" },
  { title: "Los Cloroplastos explicados de forma sencilla", cat: "Biología", path: "biologie/chloroplasten.html", keywords: "cloroplastos fotosintesis clorofila celula vegetal oxigeno" },
  { title: "Las Mitocondrias explicadas de forma sencilla", cat: "Biología", path: "biologie/mitochondrien.html", keywords: "mitocondrias central energetica celula atp energia biologia celular" },
  { title: "La Respiración Celular explicada de forma sencilla", cat: "Biología", path: "biologie/zellatmung.html", keywords: "respiracion celular atp energia mitocondrias oxigeno fotosintesis" },
  { title: "El Ecosistema explicado de forma sencilla", cat: "Biología", path: "biologie/oekosystem.html", keywords: "ecosistema ecologia cadena alimentaria productores consumidores descomponedores" },
  { title: "El Ecosistema Forestal explicado de forma sencilla", cat: "Biología", path: "biologie/waldoekosystem.html", keywords: "bosque ecosistema forestal dosel suelo ecologia" },
  { title: "El Río como Ecosistema explicado de forma sencilla", cat: "Biología", path: "biologie/fluss.html", keywords: "rio ecosistema nacimiento desembocadura ecologia curso de agua" },
  { title: "Los Cromosomas explicados de forma sencilla", cat: "Biología", path: "biologie/chromosomen.html", keywords: "cromosomas genetica adn genes cariotipo sindrome de down" },
  { title: "Por Qué Biológicamente Hay Dos Sexos", cat: "Biología", path: "biologie/warum-zwei-geschlechter.html", keywords: "sexo gametos ovulo espermatozoide anisogamia biologia evolutiva" },
  { title: "La Radiactividad explicada de forma sencilla", cat: "Química", path: "chemie/radioaktivitaet.html", keywords: "radiactividad alfa beta gamma radiacion vida media quimica nuclear" },
  { title: "La Anomalía del Agua explicada de forma sencilla", cat: "Química", path: "chemie/anomalie-des-wassers.html", keywords: "anomalia agua densidad hielo flotar congelar" }
];
