var LE_TOPICS = [
  { title: "Pythagorean Theorem Explained Simply", cat: "Math", path: "mathematik/satz-des-pythagoras.html", keywords: "pythagorean theorem triangle hypotenuse leg geometry right angle" },
  { title: "Fractions Explained Simply", cat: "Math", path: "mathematik/brueche.html", keywords: "fractions numerator denominator add fraction" },
  { title: "Prime Numbers Explained Simply", cat: "Math", path: "mathematik/primzahlen.html", keywords: "prime number number theory divisible" },
  { title: "The Monty Hall Problem Explained Simply", cat: "Math", path: "mathematik/drei-tueren-problem.html", keywords: "monty hall problem probability doors goat" },
  { title: "Why Is Every Shuffled Card Order Unique?", cat: "Math", path: "mathematik/kartenspiel-wahrscheinlichkeit.html", keywords: "card deck shuffle factorial 52 probability" },
  { title: "Gravity Explained Simply: Why a Fired Bullet Lands Just as Fast as a Dropped One", cat: "Physics", path: "physik/gravitation-abschuss.html", keywords: "gravity bullet drop projectile motion" },
  { title: "Falling Speed Explained Simply", cat: "Physics", path: "physik/fallgeschwindigkeit.html", keywords: "free fall speed falling" },
  { title: "Tides Explained Simply", cat: "Physics", path: "physik/ebbe-und-flut.html", keywords: "tides moon high tide low tide" },
  { title: "Why the Earth Is a Sphere, Not a Disc", cat: "Physics", path: "physik/erde-ist-eine-kugel.html", keywords: "earth sphere disc astronomy round" },
  { title: "The Difference Between Volts, Amps, and Watts Explained Simply", cat: "Physics", path: "physik/volt-ampere-watt.html", keywords: "volt ampere watt electricity voltage current power" },
  { title: "Mass and Density Explained Simply", cat: "Physics", path: "physik/masse-und-dichte.html", keywords: "mass density weight volume float sink" },
  { title: "Leverage (The Law of the Lever) Explained Simply", cat: "Physics", path: "physik/hebelwirkung.html", keywords: "lever law of the lever seesaw force arm" },
  { title: "Centripetal and Centrifugal Force Explained Simply", cat: "Physics", path: "physik/zentripetalkraft-zentrifugalkraft.html", keywords: "centripetal force centrifugal force circular motion curve" },
  { title: "Schrödinger's Cat Explained Simply", cat: "Physics", path: "physik/schroedingers-katze.html", keywords: "schrodinger cat quantum mechanics superposition quantum physics" },
  { title: "Water Displacement Explained Simply", cat: "Physics", path: "physik/wasserverdraengung.html", keywords: "water displacement archimedes buoyancy float sink density" },
  { title: "Darwin and the Theory of Evolution Explained Simply", cat: "Biology", path: "biologie/evolutionstheorie.html", keywords: "darwin evolution natural selection mutation species" },
  { title: "DNA Explained Simply", cat: "Biology", path: "biologie/dna.html", keywords: "dna genome double helix genes base pairs genetics" },
  { title: "Viruses Explained Simply", cat: "Biology", path: "biologie/viren.html", keywords: "viruses virus microbiology host cell vaccine genetic material" },
  { title: "Bacteria Explained Simply", cat: "Biology", path: "biologie/bakterien.html", keywords: "bacteria microbiology prokaryotes cell division antibiotics" },
  { title: "Stem Cells Explained Simply", cat: "Biology", path: "biologie/stammzellen.html", keywords: "stem cells cell biology embryonic adult bone marrow" },
  { title: "Chloroplasts Explained Simply", cat: "Biology", path: "biologie/chloroplasten.html", keywords: "chloroplasts photosynthesis chlorophyll plant cell oxygen" },
  { title: "Mitochondria Explained Simply", cat: "Biology", path: "biologie/mitochondrien.html", keywords: "mitochondria powerhouse cell atp energy cell biology" },
  { title: "Cellular Respiration Explained Simply", cat: "Biology", path: "biologie/zellatmung.html", keywords: "cellular respiration atp energy mitochondria oxygen photosynthesis" },
  { title: "Ecosystems Explained Simply", cat: "Biology", path: "biologie/oekosystem.html", keywords: "ecosystem ecology food chain producers consumers decomposers" },
  { title: "Forest Ecosystems Explained Simply", cat: "Biology", path: "biologie/waldoekosystem.html", keywords: "forest ecosystem canopy ground layer ecology" },
  { title: "Rivers as Ecosystems Explained Simply", cat: "Biology", path: "biologie/fluss.html", keywords: "river ecosystem source mouth ecology waterway" },
  { title: "Chromosomes Explained Simply", cat: "Biology", path: "biologie/chromosomen.html", keywords: "chromosomes genetics dna genes karyotype down syndrome" },
  { title: "Why There Are Biologically Two Sexes", cat: "Biology", path: "biologie/warum-zwei-geschlechter.html", keywords: "sex gametes egg cell sperm anisogamy evolutionary biology" }
];
