var LE_TOPICS = [
  { title: "Pythagorean Theorem Explained Simply", cat: "Math", path: "mathematik/satz-des-pythagoras.html", keywords: "pythagorean theorem triangle hypotenuse leg geometry right angle" },
  { title: "Fractions Explained Simply", cat: "Math", path: "mathematik/brueche.html", keywords: "fractions numerator denominator add fraction" },
  { title: "Prime Numbers Explained Simply", cat: "Math", path: "mathematik/primzahlen.html", keywords: "prime number number theory divisible" },
  { title: "The Monty Hall Problem Explained Simply", cat: "Math", path: "mathematik/drei-tueren-problem.html", keywords: "monty hall problem probability doors goat" },
  { title: "Why Is Every Shuffled Card Order Unique?", cat: "Math", path: "mathematik/kartenspiel-wahrscheinlichkeit.html", keywords: "card deck shuffle factorial 52 probability" },
  { title: "Gravity Explained Simply: Why a Fired Bullet Lands Just as Fast as a Dropped One", cat: "Physics", path: "physik/gravitation-abschuss.html", keywords: "gravity bullet drop projectile motion" },
  { title: "Falling Speed Explained Simply", cat: "Physics", path: "physik/fallgeschwindigkeit.html", keywords: "free fall speed falling" },
  { title: "Tides Explained Simply", cat: "Physics", path: "physik/ebbe-und-flut.html", keywords: "tides moon high tide low tide" },
  { title: "Why the Earth Is a Sphere, Not a Disc", cat: "Physics", path: "physik/erde-ist-eine-kugel.html", keywords: "earth sphere disc astronomy round" },
  { title: "The Difference Between Volts, Amps, and Watts Explained Simply", cat: "Physics", path: "physik/volt-ampere-watt.html", keywords: "volt ampere watt electricity voltage current power" },
  { title: "Mass and Density Explained Simply", cat: "Physics", path: "physik/masse-und-dichte.html", keywords: "mass density weight volume float sink" },
  { title: "Leverage (The Law of the Lever) Explained Simply", cat: "Physics", path: "physik/hebelwirkung.html", keywords: "lever law of the lever seesaw force arm" },
  { title: "Centripetal and Centrifugal Force Explained Simply", cat: "Physics", path: "physik/zentripetalkraft-zentrifugalkraft.html", keywords: "centripetal force centrifugal force circular motion curve" },
  { title: "Schrödinger's Cat Explained Simply", cat: "Physics", path: "physik/schroedingers-katze.html", keywords: "schrodinger cat quantum mechanics superposition quantum physics" },
  { title: "Water Displacement Explained Simply", cat: "Physics", path: "physik/wasserverdraengung.html", keywords: "water displacement archimedes buoyancy float sink density" },
  { title: "Law of Conservation of Energy Explained Simply", cat: "Physics", path: "physik/energieerhaltungssatz.html", keywords: "conservation of energy law thermodynamics heat transformation fire" },
  { title: "Darwin and the Theory of Evolution Explained Simply", cat: "Biology", path: "biologie/evolutionstheorie.html", keywords: "darwin evolution natural selection mutation species" },
  { title: "DNA Explained Simply", cat: "Biology", path: "biologie/dna.html", keywords: "dna genome double helix genes base pairs genetics" },
  { title: "Viruses Explained Simply", cat: "Biology", path: "biologie/viren.html", keywords: "viruses virus microbiology host cell vaccine genetic material" },
  { title: "Bacteria Explained Simply", cat: "Biology", path: "biologie/bakterien.html", keywords: "bacteria microbiology prokaryotes cell division antibiotics" },
  { title: "Stem Cells Explained Simply", cat: "Biology", path: "biologie/stammzellen.html", keywords: "stem cells cell biology embryonic adult bone marrow" },
  { title: "Chloroplasts Explained Simply", cat: "Biology", path: "biologie/chloroplasten.html", keywords: "chloroplasts photosynthesis chlorophyll plant cell oxygen" },
  { title: "Photosynthesis Explained Simply", cat: "Biology", path: "biologie/fotosynthese.html", keywords: "photosynthesis light reactions calvin cycle atp limiting factors" },
  { title: "Mitochondria Explained Simply", cat: "Biology", path: "biologie/mitochondrien.html", keywords: "mitochondria powerhouse cell atp energy cell biology" },
  { title: "Cellular Respiration Explained Simply", cat: "Biology", path: "biologie/zellatmung.html", keywords: "cellular respiration atp energy mitochondria oxygen photosynthesis" },
  { title: "Ecosystems Explained Simply", cat: "Biology", path: "biologie/oekosystem.html", keywords: "ecosystem ecology food chain producers consumers decomposers" },
  { title: "Forest Ecosystems Explained Simply", cat: "Biology", path: "biologie/waldoekosystem.html", keywords: "forest ecosystem canopy ground layer ecology" },
  { title: "Rivers as Ecosystems Explained Simply", cat: "Biology", path: "biologie/fluss.html", keywords: "river ecosystem source mouth ecology waterway" },
  { title: "Chromosomes Explained Simply", cat: "Biology", path: "biologie/chromosomen.html", keywords: "chromosomes genetics dna genes karyotype down syndrome" },
  { title: "Why There Are Biologically Two Sexes", cat: "Biology", path: "biologie/warum-zwei-geschlechter.html", keywords: "sex gametes egg cell sperm anisogamy evolutionary biology" },
  { title: "Neurons and the All-or-None Principle Explained Simply", cat: "Biology", path: "biologie/nervenzelle.html", keywords: "neuron nerve cell axon dendrites synapse action potential all or none principle muscle" },
  { title: "Radioactivity Explained Simply", cat: "Chemistry", path: "chemie/radioaktivitaet.html", keywords: "radioactivity alpha beta gamma radiation half-life nuclear chemistry" },
  { title: "The Anomaly of Water Explained Simply", cat: "Chemistry", path: "chemie/anomalie-des-wassers.html", keywords: "anomaly water density ice float freeze" },
  { title: "The Three States of Matter Explained Simply", cat: "Chemistry", path: "chemie/aggregatzustaende.html", keywords: "states of matter solid liquid gas melting point boiling point water iron gold silver glass particle model" }
,
  { title: "Percentages Explained Simply", cat: "Math", path: "mathematik/prozentrechnung.html", keywords: "percent percentage discount interest percentage calculation" },
  { title: "Sine, Cosine and Tangent Explained Simply", cat: "Math", path: "mathematik/trigonometrie.html", keywords: "sine cosine tangent trigonometry opposite adjacent hypotenuse angle triangle" },
  { title: "Binomial Formulas Explained Simply", cat: "Math", path: "mathematik/binomische-formeln.html", keywords: "binomial formula algebra expand square special products" },
  { title: "Exponential Growth Explained Simply", cat: "Math", path: "mathematik/exponentielles-wachstum.html", keywords: "exponential growth compound interest bacteria growth rate doubling exponential function" },
  { title: "The Birthday Paradox Explained Simply", cat: "Math", path: "mathematik/geburtstagsparadoxon.html", keywords: "birthday paradox probability statistics birthday problem" },
  { title: "Area and Volume Formulas Explained Simply", cat: "Math", path: "mathematik/flaechen-und-volumenformeln.html", keywords: "circle area sphere volume cylinder volume radius pi volume area geometry solids" }
,
  { title: "The Stone Age Explained Simply", cat: "History", path: "geschichte/steinzeit.html", keywords: "stone age paleolithic neolithic neanderthal homo sapiens neolithic revolution cave painting lascaux altamira" },
  { title: "Alexander the Great Explained Simply", cat: "History", path: "geschichte/alexander-der-grosse.html", keywords: "alexander the great macedonia persian empire issus gaugamela hellenism diadochi alexandria" },
  { title: "Rome vs. Carthage - The Punic Wars Explained Simply", cat: "History", path: "geschichte/rom-gegen-karthago.html", keywords: "punic wars rome carthage hannibal cannae zama alps crossing scipio" },
  { title: "The Roman Empire Explained Simply", cat: "History", path: "geschichte/roemisches-reich.html", keywords: "roman empire rome ancient history augustus caesar pax romana fall migration period" },
  { title: "Spanish Colonialism in the Americas Explained Simply", cat: "History", path: "geschichte/spanischer-kolonialismus.html", keywords: "spanish colonialism columbus aztec inca cortes pizarro requerimiento las casas encomienda potosi" },
  { title: "The French Revolution Explained Simply", cat: "History", path: "geschichte/franzoesische-revolution.html", keywords: "french revolution bastille tennis court oath rights of man robespierre reign of terror louis guillotine" },
  { title: "World War I Explained Simply", cat: "History", path: "geschichte/erster-weltkrieg.html", keywords: "world war 1 wwi first world war 1914 1918 july crisis sarajevo assassination franz ferdinand alliance system triple entente arms race trench warfare treaty of versailles" },
  { title: "World War II Explained Simply", cat: "History", path: "geschichte/zweiter-weltkrieg.html", keywords: "world war 2 wwii second world war 1939 1945 hitler nazi germany holocaust invasion of poland blitzkrieg stalingrad pearl harbor normandy hiroshima nagasaki wannsee conference" },
  { title: "Maximal strength explained simply", cat: "Sports Theory", path: "sporttheorie/maximalkraft.html", keywords: "maximal strength force muscle nervous system recruitment training one rep max" },
  { title: "Explosive strength explained simply", cat: "Sports Theory", path: "sporttheorie/explosivkraft.html", keywords: "explosive strength power rate of force development jump sprint plyometrics training" },
  { title: "Strength endurance explained simply", cat: "Sports Theory", path: "sporttheorie/kraftausdauer.html", keywords: "strength endurance repetitions lactate mitochondria energy fatigue training" },
  { title: "Hypertrophy explained simply", cat: "Sports Theory", path: "sporttheorie/hypertrophie.html", keywords: "hypertrophy muscle growth recovery cell nuclei muscle memory training" },
  { title: "Flexibility explained simply", cat: "Sports Theory", path: "sporttheorie/beweglichkeit.html", keywords: "flexibility stretching mobility joint range of motion warm up" },
  { title: "Atomic Structure and the Periodic Table Explained Simply", cat: "Chemistry", path: "chemie/atombau-und-periodensystem.html", keywords: "atom nucleus proton neutron electron shell valence electrons atomic number mass number isotope octet rule noble gas group period periodic table" },
  { title: "Acids, Bases and the pH Scale Explained Simply", cat: "Chemistry", path: "chemie/saeuren-und-basen.html", keywords: "acid base ph scale hydronium hydroxide bronsted indicator litmus red cabbage neutralisation salt tooth enamel logarithm" },
  { title: "Chemical Bonding Explained Simply", cat: "Chemistry", path: "chemie/chemische-bindung.html", keywords: "chemical bond ionic covalent metallic bonding electronegativity dipole hydrogen bond ionic lattice electron sea polar non-polar" },
  { title: "Redox Reactions Explained Simply", cat: "Chemistry", path: "chemie/redoxreaktionen.html", keywords: "redox oxidation reduction electron transfer oxidation number reducing agent oxidising agent reactivity series noble rusting battery daniell cell sacrificial anode" },
  { title: "Salts and Ions Explained Simply", cat: "Chemistry", path: "chemie/salze-und-ionen.html", keywords: "salt ion cation anion ionic lattice formula charge balance sulfate nitrate carbonate hydroxide ammonium hydration shell electrolyte road salt freezing point" },
  { title: "The Mole and Amount of Substance Explained Simply", cat: "Chemistry", path: "chemie/mol-und-stoffmenge.html", keywords: "mole amount of substance molar mass avogadro constant particle number molar volume stoichiometry grams periodic table" },
  { title: "Endurance and VO2max explained simply", cat: "Sports Theory", path: "sporttheorie/ausdauer.html", keywords: "endurance vo2max maximal oxygen uptake fick principle cardiac output stroke volume anaerobic threshold lactate karvonen interval method athletes heart" },
];
