var LE_TOPICS = [
  { title: "Satz des Pythagoras leicht erklaert", cat: "Mathematik", path: "mathematik/satz-des-pythagoras.html", keywords: "pythagoras dreieck hypotenuse kathete geometrie rechtwinklig" },
  { title: "Brueche leicht erklaert", cat: "Mathematik", path: "mathematik/brueche.html", keywords: "bruchrechnung zaehler nenner bruch addieren" },
  { title: "Primzahlen leicht erklaert", cat: "Mathematik", path: "mathematik/primzahlen.html", keywords: "primzahl zahlentheorie teilbar" },
  { title: "Das Drei-Tueren-Problem (Monty Hall) leicht erklaert", cat: "Mathematik", path: "mathematik/drei-tueren-problem.html", keywords: "monty hall ziegenproblem wahrscheinlichkeit stochastik tueren" },
  { title: "Warum ist jede gemischte Kartenreihenfolge einzigartig", cat: "Mathematik", path: "mathematik/kartenspiel-wahrscheinlichkeit.html", keywords: "kartenspiel karten mischen fakultaet 52 wahrscheinlichkeit stochastik" },
  { title: "Warum eine abgefeuerte Kugel genauso schnell landet wie eine fallengelassene", cat: "Physik", path: "physik/gravitation-abschuss.html", keywords: "gravitation schwerkraft wurf abschuss kugel" },
  { title: "Fallgeschwindigkeit leicht erklaert", cat: "Physik", path: "physik/fallgeschwindigkeit.html", keywords: "freier fall geschwindigkeit fallen" },
  { title: "Ebbe und Flut leicht erklaert", cat: "Physik", path: "physik/ebbe-und-flut.html", keywords: "gezeiten mond ebbe flut" },
  { title: "Warum die Erde eine Kugel ist und keine Scheibe", cat: "Physik", path: "physik/erde-ist-eine-kugel.html", keywords: "erde kugel scheibe astronomie rund" },
  { title: "Unterschied zwischen Volt, Ampere und Watt", cat: "Physik", path: "physik/volt-ampere-watt.html", keywords: "volt ampere watt strom elektrizitaet spannung stromstaerke leistung elektro" },
  { title: "Masse und Dichte leicht erklaert", cat: "Physik", path: "physik/masse-und-dichte.html", keywords: "masse dichte gewicht volumen schwimmen sinken" },
  { title: "Hebelwirkung (Hebelgesetz) leicht erklaert", cat: "Physik", path: "physik/hebelwirkung.html", keywords: "hebel hebelgesetz wippe kraftarm lastarm" },
  { title: "Zentripetalkraft und Zentrifugalkraft leicht erklaert", cat: "Physik", path: "physik/zentripetalkraft-zentrifugalkraft.html", keywords: "zentripetalkraft zentrifugalkraft kreisbewegung scheinkraft kurve" },
  { title: "Schroedingers Katze leicht erklaert", cat: "Physik", path: "physik/schroedingers-katze.html", keywords: "schroedinger katze quantenmechanik superposition ueberlagerung quantenphysik" },
  { title: "Wasserverdraengung leicht erklaert", cat: "Physik", path: "physik/wasserverdraengung.html", keywords: "wasserverdraengung archimedes auftrieb schwimmen sinken dichte" },
  { title: "Darwin und die Evolutionstheorie leicht erklaert", cat: "Biologie", path: "biologie/evolutionstheorie.html", keywords: "darwin evolution evolutionstheorie natuerliche selektion mutation art" },
  { title: "DNA leicht erklaert", cat: "Biologie", path: "biologie/dna.html", keywords: "dna erbgut doppelhelix gene basenpaare genetik" },
  { title: "Viren leicht erklaert", cat: "Biologie", path: "biologie/viren.html", keywords: "viren virus mikrobiologie wirtszelle impfung erbgut" },
  { title: "Bakterien leicht erklaert", cat: "Biologie", path: "biologie/bakterien.html", keywords: "bakterien mikrobiologie prokaryoten zellteilung antibiotika" },
  { title: "Stammzellen leicht erklaert", cat: "Biologie", path: "biologie/stammzellen.html", keywords: "stammzellen zellbiologie embryonal adult knochenmark" },
  { title: "Chloroplasten leicht erklaert", cat: "Biologie", path: "biologie/chloroplasten.html", keywords: "chloroplasten fotosynthese chlorophyll pflanzenzelle sauerstoff" },
  { title: "Mitochondrien leicht erklaert", cat: "Biologie", path: "biologie/mitochondrien.html", keywords: "mitochondrien kraftwerk zelle atp energie zellbiologie" },
  { title: "Zellatmung leicht erklaert", cat: "Biologie", path: "biologie/zellatmung.html", keywords: "zellatmung atp energie mitochondrien sauerstoff fotosynthese" },
  { title: "Oekosystem leicht erklaert", cat: "Biologie", path: "biologie/oekosystem.html", keywords: "oekosystem oekologie nahrungskette produzenten konsumenten destruenten" },
  { title: "Waldoekosystem leicht erklaert", cat: "Biologie", path: "biologie/waldoekosystem.html", keywords: "wald waldoekosystem baumkronen bodenschicht oekologie" },
  { title: "Der Fluss als Oekosystem leicht erklaert", cat: "Biologie", path: "biologie/fluss.html", keywords: "fluss oekosystem quelle muendung oekologie gewaesser" },
  { title: "Chromosomen leicht erklaert", cat: "Biologie", path: "biologie/chromosomen.html", keywords: "chromosomen genetik dna gene karyogramm down-syndrom" },
  { title: "Warum es biologisch zwei Geschlechter gibt", cat: "Biologie", path: "biologie/warum-zwei-geschlechter.html", keywords: "geschlecht gameten eizelle spermium anisogamie evolutionsbiologie" }
];
