var LE_TOPICS = [
  { title: "Satz des Pythagoras leicht erklaert", cat: "Mathematik", path: "mathematik/satz-des-pythagoras.html", keywords: "pythagoras dreieck hypotenuse kathete geometrie rechtwinklig" },
  { title: "Brueche leicht erklaert", cat: "Mathematik", path: "mathematik/brueche.html", keywords: "bruchrechnung zaehler nenner bruch addieren" },
  { title: "Primzahlen leicht erklaert", cat: "Mathematik", path: "mathematik/primzahlen.html", keywords: "primzahl zahlentheorie teilbar" },
  { title: "Das Drei-Tueren-Problem (Monty Hall) leicht erklaert", cat: "Mathematik", path: "mathematik/drei-tueren-problem.html", keywords: "monty hall ziegenproblem wahrscheinlichkeit stochastik tueren" },
  { title: "Warum ist jede gemischte Kartenreihenfolge einzigartig", cat: "Mathematik", path: "mathematik/kartenspiel-wahrscheinlichkeit.html", keywords: "kartenspiel karten mischen fakultaet 52 wahrscheinlichkeit stochastik" },
  { title: "Warum eine abgefeuerte Kugel genauso schnell landet wie eine fallengelassene", cat: "Physik", path: "physik/gravitation-abschuss.html", keywords: "gravitation schwerkraft wurf abschuss kugel" },
  { title: "Fallgeschwindigkeit leicht erklaert", cat: "Physik", path: "physik/fallgeschwindigkeit.html", keywords: "freier fall geschwindigkeit fallen" },
  { title: "Ebbe und Flut leicht erklaert", cat: "Physik", path: "physik/ebbe-und-flut.html", keywords: "gezeiten mond ebbe flut" },
  { title: "Warum die Erde eine Kugel ist und keine Scheibe", cat: "Physik", path: "physik/erde-ist-eine-kugel.html", keywords: "erde kugel scheibe astronomie rund" },
  { title: "Unterschied zwischen Volt, Ampere und Watt", cat: "Physik", path: "physik/volt-ampere-watt.html", keywords: "volt ampere watt strom elektrizitaet spannung stromstaerke leistung elektro" },
  { title: "Masse und Dichte leicht erklaert", cat: "Physik", path: "physik/masse-und-dichte.html", keywords: "masse dichte gewicht volumen schwimmen sinken" },
  { title: "Hebelwirkung (Hebelgesetz) leicht erklaert", cat: "Physik", path: "physik/hebelwirkung.html", keywords: "hebel hebelgesetz wippe kraftarm lastarm" },
  { title: "Zentripetalkraft und Zentrifugalkraft leicht erklaert", cat: "Physik", path: "physik/zentripetalkraft-zentrifugalkraft.html", keywords: "zentripetalkraft zentrifugalkraft kreisbewegung scheinkraft kurve" },
  { title: "Schroedingers Katze leicht erklaert", cat: "Physik", path: "physik/schroedingers-katze.html", keywords: "schroedinger katze quantenmechanik superposition ueberlagerung quantenphysik" },
  { title: "Wasserverdraengung leicht erklaert", cat: "Physik", path: "physik/wasserverdraengung.html", keywords: "wasserverdraengung archimedes auftrieb schwimmen sinken dichte" },
  { title: "Energieerhaltungssatz leicht erklaert", cat: "Physik", path: "physik/energieerhaltungssatz.html", keywords: "energieerhaltungssatz energie erhaltungssatz thermodynamik hauptsatz waerme umwandlung feuer" },
  { title: "Darwin und die Evolutionstheorie leicht erklaert", cat: "Biologie", path: "biologie/evolutionstheorie.html", keywords: "darwin evolution evolutionstheorie natuerliche selektion mutation art" },
  { title: "DNA leicht erklaert", cat: "Biologie", path: "biologie/dna.html", keywords: "dna erbgut doppelhelix gene basenpaare genetik" },
  { title: "Viren leicht erklaert", cat: "Biologie", path: "biologie/viren.html", keywords: "viren virus mikrobiologie wirtszelle impfung erbgut" },
  { title: "Bakterien leicht erklaert", cat: "Biologie", path: "biologie/bakterien.html", keywords: "bakterien mikrobiologie prokaryoten zellteilung antibiotika" },
  { title: "Stammzellen leicht erklaert", cat: "Biologie", path: "biologie/stammzellen.html", keywords: "stammzellen zellbiologie embryonal adult knochenmark" },
  { title: "Chloroplasten leicht erklaert", cat: "Biologie", path: "biologie/chloroplasten.html", keywords: "chloroplasten fotosynthese chlorophyll pflanzenzelle sauerstoff" },
  { title: "Fotosynthese leicht erklaert", cat: "Biologie", path: "biologie/fotosynthese.html", keywords: "fotosynthese lichtreaktion calvin-zyklus atp begrenzende faktoren" },
  { title: "Mitochondrien leicht erklaert", cat: "Biologie", path: "biologie/mitochondrien.html", keywords: "mitochondrien kraftwerk zelle atp energie zellbiologie" },
  { title: "Zellatmung leicht erklaert", cat: "Biologie", path: "biologie/zellatmung.html", keywords: "zellatmung atp energie mitochondrien sauerstoff fotosynthese" },
  { title: "Oekosystem leicht erklaert", cat: "Biologie", path: "biologie/oekosystem.html", keywords: "oekosystem oekologie nahrungskette produzenten konsumenten destruenten" },
  { title: "Waldoekosystem leicht erklaert", cat: "Biologie", path: "biologie/waldoekosystem.html", keywords: "wald waldoekosystem baumkronen bodenschicht oekologie" },
  { title: "Der Fluss als Oekosystem leicht erklaert", cat: "Biologie", path: "biologie/fluss.html", keywords: "fluss oekosystem quelle muendung oekologie gewaesser" },
  { title: "Chromosomen leicht erklaert", cat: "Biologie", path: "biologie/chromosomen.html", keywords: "chromosomen genetik dna gene karyogramm down-syndrom" },
  { title: "Warum es biologisch zwei Geschlechter gibt", cat: "Biologie", path: "biologie/warum-zwei-geschlechter.html", keywords: "geschlecht gameten eizelle spermium anisogamie evolutionsbiologie" },
  { title: "Die Nervenzelle und das Alles-oder-Nichts-Prinzip leicht erklaert", cat: "Biologie", path: "biologie/nervenzelle.html", keywords: "nervenzelle neuron axon dendriten synapse aktionspotenzial alles oder nichts prinzip nerv muskel" },
  { title: "Radioaktivitaet leicht erklaert", cat: "Chemie", path: "chemie/radioaktivitaet.html", keywords: "radioaktivitaet alpha beta gamma strahlung halbwertszeit kernchemie" },
  { title: "Die Anomalie des Wassers leicht erklaert", cat: "Chemie", path: "chemie/anomalie-des-wassers.html", keywords: "anomalie wasser dichte eis schwimmen gefrieren" },
  { title: "Die drei Aggregatzustaende leicht erklaert", cat: "Chemie", path: "chemie/aggregatzustaende.html", keywords: "aggregatzustaende fest fluessig gasfoermig schmelzpunkt siedepunkt wasser eisen gold silber glas teilchenmodell" }
,
  { title: "Prozentrechnung leicht erklärt", cat: "Mathematik", path: "mathematik/prozentrechnung.html", keywords: "prozent prozentrechnung rabatt zinsen prozentsatz grundwert prozentwert" },
  { title: "Sinus, Cosinus und Tangens leicht erklärt", cat: "Mathematik", path: "mathematik/trigonometrie.html", keywords: "sinus cosinus tangens trigonometrie gegenkathete ankathete hypotenuse winkel dreieck" },
  { title: "Binomische Formeln leicht erklärt", cat: "Mathematik", path: "mathematik/binomische-formeln.html", keywords: "binomische formel binomialformel algebra ausmultiplizieren quadrat quadratische ergaenzung" },
  { title: "Exponentielles Wachstum leicht erklärt", cat: "Mathematik", path: "mathematik/exponentielles-wachstum.html", keywords: "exponentielles wachstum zinseszins bakterien wachstumsrate verdopplung exponentialfunktion" },
  { title: "Das Geburtstagsparadoxon leicht erklärt", cat: "Mathematik", path: "mathematik/geburtstagsparadoxon.html", keywords: "geburtstagsparadoxon wahrscheinlichkeit stochastik geburtstag paradox" },
  { title: "Flächen- und Volumenformeln leicht erklärt", cat: "Mathematik", path: "mathematik/flaechen-und-volumenformeln.html", keywords: "kreisflaeche kugelvolumen zylindervolumen radius pi volumen flaeche geometrie koerper" }
,
  { title: "Die Steinzeit leicht erklärt", cat: "Geschichte", path: "geschichte/steinzeit.html", keywords: "steinzeit altsteinzeit jungsteinzeit neandertaler homo sapiens neolithische revolution hoehlenmalerei lascaux altamira" },
  { title: "Alexander der Große leicht erklärt", cat: "Geschichte", path: "geschichte/alexander-der-grosse.html", keywords: "alexander der grosse makedonien perserreich issos gaugamela hellenismus diadochen alexandria" },
  { title: "Rom gegen Karthago - die Punischen Kriege leicht erklärt", cat: "Geschichte", path: "geschichte/rom-gegen-karthago.html", keywords: "punische kriege rom karthago hannibal cannae zama alpenueberquerung scipio" },
  { title: "Das Römische Reich leicht erklärt", cat: "Geschichte", path: "geschichte/roemisches-reich.html", keywords: "roemisches reich rom antike augustus caesar pax romana untergang voelkerwanderung" },
  { title: "Spanischer Kolonialismus in Amerika leicht erklärt", cat: "Geschichte", path: "geschichte/spanischer-kolonialismus.html", keywords: "kolonialismus spanien kolumbus azteken inka cortes pizarro requerimiento las casas encomienda potosi" },
  { title: "Die Französische Revolution leicht erklärt", cat: "Geschichte", path: "geschichte/franzoesische-revolution.html", keywords: "franzoesische revolution bastille ballhausschwur menschenrechte robespierre terrorherrschaft ludwig guillotine" },
  { title: "Der Erste Weltkrieg leicht erklärt", cat: "Geschichte", path: "geschichte/erster-weltkrieg.html", keywords: "erster weltkrieg 1914 1918 julikrise sarajevo attentat franz ferdinand buendnissysteme dreibund triple entente nationalismus wettruesten stellungskrieg versailler vertrag" },
  { title: "Der Zweite Weltkrieg leicht erklärt", cat: "Geschichte", path: "geschichte/zweiter-weltkrieg.html", keywords: "zweiter weltkrieg 1939 1945 hitler machtuebernahme nationalsozialismus holocaust shoah ueberfall auf polen blitzkrieg stalingrad pearl harbor normandie hiroshima nagasaki wannseekonferenz" },
  { title: "Maximalkraft leicht erklaert", cat: "Sporttheorie", path: "sporttheorie/maximalkraft.html", keywords: "maximalkraft absolutkraft kraftdefizit rekrutierung frequenzierung synchronisation henneman groessenordnungsprinzip fasertypen belastungsnormative abitur" },
  { title: "Explosivkraft und Schnellkraft leicht erklaert", cat: "Sporttheorie", path: "sporttheorie/explosivkraft.html", keywords: "explosivkraft schnellkraft kraftstoss kraft zeit kurve startkraft kraftanstiegsrate reaktivkraft dehnungs verkuerzungs zyklus plyometrie abitur" },
  { title: "Kraftausdauer leicht erklaert", cat: "Sporttheorie", path: "sporttheorie/kraftausdauer.html", keywords: "kraftausdauer energiebereitstellung kreatinphosphat glykolyse laktat azidose pufferkapazitaet flussrate kapazitaet abitur" },
  { title: "Hypertrophie leicht erklaert", cat: "Sporttheorie", path: "sporttheorie/hypertrophie.html", keywords: "hypertrophie superkompensation fitness fatigue satellitenzellen myonuklei mtor proteinbilanz volumen belastungsnormative abitur" },
  { title: "Beweglichkeit leicht erklaert", cat: "Sporttheorie", path: "sporttheorie/beweglichkeit.html", keywords: "beweglichkeit gelenkigkeit dehnfaehigkeit muskelspindel golgi sehnenorgan autogene hemmung pnf dehnungstoleranz abitur" },
  { title: "Atombau und Periodensystem leicht erklaert", cat: "Chemie", path: "chemie/atombau-und-periodensystem.html", keywords: "atom atombau periodensystem proton neutron elektron schale valenzelektronen ordnungszahl massenzahl isotope oktettregel edelgas hauptgruppe periode" },
  { title: "Saeuren, Basen und der pH-Wert leicht erklaert", cat: "Chemie", path: "chemie/saeuren-und-basen.html", keywords: "saeure base ph wert oxonium hydroxid broensted indikator lackmus rotkohl neutralisation salz zahnschmelz logarithmus" },
  { title: "Chemische Bindung leicht erklaert", cat: "Chemie", path: "chemie/chemische-bindung.html", keywords: "chemische bindung ionenbindung elektronenpaarbindung atombindung metallbindung elektronegativitaet dipol wasserstoffbruecke ionengitter elektronengas polar unpolar" },
  { title: "Redoxreaktionen leicht erklaert", cat: "Chemie", path: "chemie/redoxreaktionen.html", keywords: "redox oxidation reduktion elektronenuebergang oxidationszahl reduktionsmittel oxidationsmittel redoxreihe spannungsreihe edel unedel rosten batterie daniell opferanode" },
];
