var LE_TOPICS = [
  { title: "El Teorema de Pitágoras explicado de forma sencilla", cat: "Matemáticas", path: "mathematik/satz-des-pythagoras.html", keywords: "teorema pitagoras triangulo hipotenusa cateto geometria angulo recto" },
  { title: "Las Fracciones explicadas de forma sencilla", cat: "Matemáticas", path: "mathematik/brueche.html", keywords: "fracciones numerador denominador sumar fraccion" },
  { title: "Los Números Primos explicados de forma sencilla", cat: "Matemáticas", path: "mathematik/primzahlen.html", keywords: "numero primo teoria de numeros divisible" },
  { title: "El Problema de Monty Hall explicado de forma sencilla", cat: "Matemáticas", path: "mathematik/drei-tueren-problem.html", keywords: "monty hall problema puertas probabilidad cabra" },
  { title: "¿Por qué cada orden de cartas barajado es único?", cat: "Matemáticas", path: "mathematik/kartenspiel-wahrscheinlichkeit.html", keywords: "cartas baraja mezclar factorial 52 probabilidad" },
  { title: "La Gravedad explicada de forma sencilla: Por qué una bala disparada aterriza tan rápido como una que se deja caer", cat: "Física", path: "physik/gravitation-abschuss.html", keywords: "gravedad bala caida disparo movimiento" },
  { title: "La Velocidad de Caída explicada de forma sencilla", cat: "Física", path: "physik/fallgeschwindigkeit.html", keywords: "caida libre velocidad caer" },
  { title: "Las Mareas explicadas de forma sencilla", cat: "Física", path: "physik/ebbe-und-flut.html", keywords: "mareas luna marea alta marea baja" },
  { title: "Por qué la Tierra es una esfera y no un disco", cat: "Física", path: "physik/erde-ist-eine-kugel.html", keywords: "tierra esfera disco astronomia redonda" },
  { title: "La Diferencia entre Voltios, Amperios y Vatios explicada de forma sencilla", cat: "Física", path: "physik/volt-ampere-watt.html", keywords: "voltio amperio vatio electricidad tension corriente potencia" },
  { title: "La Masa y la Densidad explicadas de forma sencilla", cat: "Física", path: "physik/masse-und-dichte.html", keywords: "masa densidad peso volumen flotar hundir" },
  { title: "La Palanca (Ley de la Palanca) explicada de forma sencilla", cat: "Física", path: "physik/hebelwirkung.html", keywords: "palanca ley de la palanca balancin brazo de fuerza" },
  { title: "La Fuerza Centrípeta y Centrífuga explicadas de forma sencilla", cat: "Física", path: "physik/zentripetalkraft-zentrifugalkraft.html", keywords: "fuerza centripeta fuerza centrifuga movimiento circular curva" },
  { title: "El Gato de Schrödinger explicado de forma sencilla", cat: "Física", path: "physik/schroedingers-katze.html", keywords: "schrodinger gato mecanica cuantica superposicion fisica cuantica" },
  { title: "El Desplazamiento de Agua explicado de forma sencilla", cat: "Física", path: "physik/wasserverdraengung.html", keywords: "desplazamiento de agua arquimedes flotabilidad flotar hundir densidad" },
  { title: "Darwin y la Teoría de la Evolución explicada de forma sencilla", cat: "Biología", path: "biologie/evolutionstheorie.html", keywords: "darwin evolucion seleccion natural mutacion especie" },
  { title: "El ADN explicado de forma sencilla", cat: "Biología", path: "biologie/dna.html", keywords: "adn genoma doble helice genes pares de bases genetica" },
  { title: "Los Virus explicados de forma sencilla", cat: "Biología", path: "biologie/viren.html", keywords: "virus microbiologia celula huesped vacuna material genetico" },
  { title: "Las Bacterias explicadas de forma sencilla", cat: "Biología", path: "biologie/bakterien.html", keywords: "bacterias microbiologia procariotas division celular antibioticos" },
  { title: "Las Células Madre explicadas de forma sencilla", cat: "Biología", path: "biologie/stammzellen.html", keywords: "celulas madre biologia celular embrionarias adultas medula osea" },
  { title: "Los Cloroplastos explicados de forma sencilla", cat: "Biología", path: "biologie/chloroplasten.html", keywords: "cloroplastos fotosintesis clorofila celula vegetal oxigeno" },
  { title: "La Fotosíntesis explicada de forma sencilla", cat: "Biología", path: "biologie/fotosynthese.html", keywords: "fotosintesis fase luminosa ciclo de calvin atp factores limitantes" },
  { title: "Las Mitocondrias explicadas de forma sencilla", cat: "Biología", path: "biologie/mitochondrien.html", keywords: "mitocondrias central energetica celula atp energia biologia celular" },
  { title: "La Respiración Celular explicada de forma sencilla", cat: "Biología", path: "biologie/zellatmung.html", keywords: "respiracion celular atp energia mitocondrias oxigeno fotosintesis" },
  { title: "El Ecosistema explicado de forma sencilla", cat: "Biología", path: "biologie/oekosystem.html", keywords: "ecosistema ecologia cadena alimentaria productores consumidores descomponedores" },
  { title: "El Ecosistema Forestal explicado de forma sencilla", cat: "Biología", path: "biologie/waldoekosystem.html", keywords: "bosque ecosistema forestal dosel suelo ecologia" },
  { title: "El Río como Ecosistema explicado de forma sencilla", cat: "Biología", path: "biologie/fluss.html", keywords: "rio ecosistema nacimiento desembocadura ecologia curso de agua" },
  { title: "Los Cromosomas explicados de forma sencilla", cat: "Biología", path: "biologie/chromosomen.html", keywords: "cromosomas genetica adn genes cariotipo sindrome de down" },
  { title: "Por Qué Biológicamente Hay Dos Sexos", cat: "Biología", path: "biologie/warum-zwei-geschlechter.html", keywords: "sexo gametos ovulo espermatozoide anisogamia biologia evolutiva" },
  { title: "La Neurona y el Principio de Todo o Nada explicado de forma sencilla", cat: "Biología", path: "biologie/nervenzelle.html", keywords: "neurona celula nerviosa axon dendritas sinapsis potencial de accion todo o nada musculo" },
  { title: "La Radiactividad explicada de forma sencilla", cat: "Química", path: "chemie/radioaktivitaet.html", keywords: "radiactividad alfa beta gamma radiacion vida media quimica nuclear" },
  { title: "La Anomalía del Agua explicada de forma sencilla", cat: "Química", path: "chemie/anomalie-des-wassers.html", keywords: "anomalia agua densidad hielo flotar congelar" },
  { title: "Los Tres Estados de la Materia explicados de forma sencilla", cat: "Química", path: "chemie/aggregatzustaende.html", keywords: "estados de la materia solido liquido gaseoso punto de fusion punto de ebullicion agua hierro oro plata vidrio modelo de particulas" }
,
  { title: "Los Porcentajes explicados de forma sencilla", cat: "Matematicas", path: "mathematik/prozentrechnung.html", keywords: "porcentaje descuento interes calculo porcentual tanto por ciento" },
  { title: "Seno, Coseno y Tangente explicados de forma sencilla", cat: "Matematicas", path: "mathematik/trigonometrie.html", keywords: "seno coseno tangente trigonometria cateto opuesto adyacente hipotenusa angulo triangulo" },
  { title: "Las Formulas de los Binomios explicadas de forma sencilla", cat: "Matematicas", path: "mathematik/binomische-formeln.html", keywords: "formula binomio algebra desarrollar cuadrado productos notables" },
  { title: "El Crecimiento Exponencial explicado de forma sencilla", cat: "Matematicas", path: "mathematik/exponentielles-wachstum.html", keywords: "crecimiento exponencial interes compuesto bacterias tasa de crecimiento duplicacion" },
  { title: "La Paradoja del Cumpleanos explicada de forma sencilla", cat: "Matematicas", path: "mathematik/geburtstagsparadoxon.html", keywords: "paradoja del cumpleanos probabilidad estadistica cumpleanos coincidencia" },
  { title: "Formulas de Area y Volumen explicadas de forma sencilla", cat: "Matematicas", path: "mathematik/flaechen-und-volumenformeln.html", keywords: "area circulo volumen esfera volumen cilindro radio pi volumen area geometria solidos" }
,
  { title: "La Edad de Piedra explicada de forma sencilla", cat: "Historia", path: "geschichte/steinzeit.html", keywords: "edad de piedra paleolitico neolitico neandertal homo sapiens revolucion neolitica pintura rupestre lascaux altamira" },
  { title: "Alejandro Magno explicado de forma sencilla", cat: "Historia", path: "geschichte/alexander-der-grosse.html", keywords: "alejandro magno macedonia imperio persa issos gaugamela helenismo diadocos alejandria" },
  { title: "Roma contra Cartago - Las Guerras Punicas explicadas de forma sencilla", cat: "Historia", path: "geschichte/rom-gegen-karthago.html", keywords: "guerras punicas roma cartago anibal canas zama alpes escipion" },
  { title: "El Imperio Romano explicado de forma sencilla", cat: "Historia", path: "geschichte/roemisches-reich.html", keywords: "imperio romano roma antiguedad augusto cesar pax romana caida invasiones barbaras" },
  { title: "El Colonialismo Espanol en America explicado de forma sencilla", cat: "Historia", path: "geschichte/spanischer-kolonialismus.html", keywords: "colonialismo espanol colon aztecas incas cortes pizarro requerimiento las casas encomienda potosi" },
  { title: "La Revolucion Francesa explicada de forma sencilla", cat: "Historia", path: "geschichte/franzoesische-revolution.html", keywords: "revolucion francesa bastilla juramento juego de pelota derechos del hombre robespierre terror luis guillotina" },
  { title: "La Primera Guerra Mundial explicada de forma sencilla", cat: "Historia", path: "geschichte/erster-weltkrieg.html", keywords: "primera guerra mundial 1914 1918 crisis de julio sarajevo atentado francisco fernando alianzas nacionalismo carrera armamentistica tratado de versalles" },
  { title: "La Segunda Guerra Mundial explicada de forma sencilla", cat: "Historia", path: "geschichte/zweiter-weltkrieg.html", keywords: "segunda guerra mundial 1939 1945 hitler nazismo holocausto invasion de polonia blitzkrieg stalingrado pearl harbor normandia hiroshima nagasaki conferencia de wannsee" }
];
